source:
  type: kafka
  kafka:
    address:
      - 192.168.80.132:9092
    topic: train-data
    group: nbt-consumer-group

sink:
  hostname: http://output-system/api
  secret: "secret"
  dataset_id: ""

logger:
  mode: development
