source:
  type: kafka
  kafka:
    address:
      - 192.168.80.132:9092
    topic: train-data
    group: nbt-consumer-group2

sink:
  url: http://output-system/api
  secret: "secret"

logger:
  mode: development
